services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cloudflare_network
    restart: always

networks:
  cloudflare_network:
    external: true
